### ISSUE TITLE
Give the embedded terminal access to host system

### ISSUE THREAD

**Issue by thiblahute** [flathub/com.visualstudio.code.oss#5]
For the terminal to be really useful it should be able to use host access (through the `HostCommand` mechanism in flatpak). This requires upstream work but I report here as I guess it is the place where I might actually have an answer about the problem).

**Comment by TingPing** [comment]
That is very much not trivial work and would require upstream to genuinely care about the sandbox'd use-case in general.

**Comment by thiblahute** [comment]
> That is very much not trivial work and would require upstream to genuinely care about the sandbox'd use-case in general.

True, but without that this flatpak is mostly useless to me :-)

**Comment by amtlib-dot-dll** [comment]
Sounds nice, but this might not be a priority for me. 😀 If you have a patch you can submit it here or directly to the upstream @thiblahute

**Comment by juhp** [comment]
Actually not just the terminal, various extensions also need to run host system tools.

**Comment by mzabaluev** [comment]
I think this and other tool running scenarios could be enabled by the following:
1. A D-Bus service that would (with some user-controlled whitelisting) run host binaries attached to caller-provided file descriptors for stdin/stdout/stderr, and provide lifecycle controls and signal proxying.
2. A "tool proxy" executable inside the container, which uses the D-Bus service to run the actual tool and serves as its container-side stand-in with regard to signals and exit status.

That's a complicated way to solve the issue, but I don't know any means for a child process to migrate from the container's namespaces out to the host.

**Comment by amtlib-dot-dll** [comment]
@mzabaluev You may just run `bwrap` directly and don't unshare the PID namespace https://github.com/projectatomic/bubblewrap/blob/master/bwrap.xml#L110

**Comment by mzabaluev** [comment]
@amtlib-dot-dll Is it possible to use bwrap inside the sandbox to get out of it? The binary is not currently available in the sandbox. Most tools also need access to the host filesystem.

**Comment by mzabaluev** [comment]
I've done some reading up, which should have been a prerequisite... So 1. above could be provided by `HostCommand` API or its suitably "portalized" derivative. What about 2? Is it feasible to provide a generic tool wrapper that would use the Flatpak D-Bus service to run processes on the host, so that Visual Studio Code and other IDEs would not need modifications for running in a sandbox? Note that the embedded terminal widget itself does not need to run on the host.

**Comment by amtlib-dot-dll** [comment]
No, I meant that
* Flatpak uses [bubblewrap](https://github.com/projectatomic/bubblewrap) (a.k.a `bwrap`) for isolation
* Flatpak instructs bubblewrap to create a new PID namespace and therefore you cannot see other processes in the host system
* Flatpak instructs bubblewrap to create a new mount namespace and replace the `/usr`, `/app`, `$(XDG_DATA_HOME)` and so on directories with the sandboxed ones, so you cannot access the real `/usr` directory
* You can call bubblewrap directly instead of running Flatpak

More info [here](https://github.com/flatpak/flatpak/wiki/Sandbox) and [here](http://docs.flatpak.org/en/latest/under-the-hood.html)

**Comment by mzabaluev** [comment]
@amtlib-dot-dll I see. I'd like a solution that would work out of the box in Flatpak without giving the app the keys to the whole kingdom.

**Comment by TingPing** [comment]
An IDE is one tool where you simply have to forego security for usablity. See GNOME-Builder on how to handle this.

**Comment by amtlib-dot-dll** [comment]
> I'd like a solution that would work out of the box in Flatpak without giving the app the keys to the whole kingdom.

> An IDE is one tool where you simply have to forego security for usablity.

:woman_shrugging:

**Comment by TingPing** [comment]
Yea it is certainly *impossible* to be sandboxed and not be sandboxed at the same time as they request. But as mentioned this requires deep redesign in the project, this isn't a toggle somebody can just make.

**Comment by amtlib-dot-dll** [comment]
Hmmm, can you add an option to share the PID namespace with the host in Flatpak? That is, remove the `--unshare-pid` of `bwrap` @TingPing @alexlarsson :thinking:

**Comment by G-Ray** [comment]
Any update on this ? I switched back to the proprietary vscode binary because some extensions need to access the host.

**Comment by Ben-Voris** [comment]
This affects more than the pid namespace. It prevents access to header files and alternative tools that aren't part of the project but aren't in the permission list. For example, this compiler exists:

```
: file /usr/bin/x86_64-w64-mingw32-gcc-win32
/usr/bin/x86_64-w64-mingw32-gcc-win32: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=d1e1d2111a6d2cdb3f872748463056e1c21cfcce, stripped
```

But the shell prompt in Visual Studio - OSS gives:

```
$ file /usr/bin/x86_64-w64-mingw32-gcc-win32
/usr/bin/x86_64-w64-mingw32-gcc-win32: cannot open `/usr/bin/x86_64-w64-mingw32-gcc-win32' (No such file or directory)
```
Some include files end up at unexpected locations, like the following. Again, the first output is from a terminal session and the second from the

```
$ find / -name winsock2.h -ls 2> /dev/null
  4466632      0 lrwxrwxrwx   1  nfsnobody nfsnobody       40 Nov 18  2017 /run/host/usr/i686-w64-mingw32/include/winsock2.h -> ../../share/mingw-w64/include/winsock2.h
  4464715     52 -rw-r--r--   1  nfsnobody nfsnobody    49590 Nov 18  2017 /run/host/usr/share/mingw-w64/include/winsock2.h
  4472138      0 lrwxrwxrwx   1  nfsnobody nfsnobody       40 Nov 18  2017 /run/host/usr/x86_64-w64-mingw32/include/winsock2.h -> ../../share/mingw-w64/include/winsock2.h

: find / -name winsock2.h -ls 2> /dev/null
  4466632      0 lrwxrwxrwx   1 root     root           40 Nov 18  2017 /usr/i686-w64-mingw32/include/winsock2.h -> ../../share/mingw-w64/include/winsock2.h
  4464715     52 -rw-r--r--   1 root     root        49590 Nov 18  2017 /usr/share/mingw-w64/include/winsock2.h
  4472138      0 lrwxrwxrwx   1 root     root           40 Nov 18  2017 /usr/x86_64-w64-mingw32/include/winsock2.h -> ../../share/mingw-w64/include/winsock2.h

$ find / -name winsock2.h -ls 2> /dev/null
  4466632      0 lrwxrwxrwx   1  nfsnobody nfsnobody       40 Nov 18  2017 /run/host/usr/i686-w64-mingw32/include/winsock2.h -> ../../share/mingw-w64/include/winsock2.h
  4464715     52 -rw-r--r--   1  nfsnobody nfsnobody    49590 Nov 18  2017 /run/host/usr/share/mingw-w64/include/winsock2.h
  4472138      0 lrwxrwxrwx   1  nfsnobody nfsnobody       40 Nov 18  2017 /run/host/usr/x86_64-w64-mingw32/include/winsock2.h -> ../../share/mingw-w64/include/winsock2.h
```

**Comment by TingPing** [comment]
Honestly I'm just going to close this as there seems to be a misunderstanding:

In order to run host binaries you must go through an abstraction like `flatpak-spawn --host some-tool`.

In order for the terminal to run on the host by default it requires contributing to vscode directly. This is not a package issue and cannot be resolved here.
