### ISSUE TITLE
Difference between oss and non-oss version

### ISSUE THREAD

**Issue by martijnkruiten** [flathub/com.visualstudio.code.oss#6]
It's not obvious for me what the difference between the two versions is. I mean, probably the oss version is compiled form source and does not include any proprietary code. But are there any other differences? Does the oss version lack certain features, or does it lack in speed, or is it based on unstable code, or...? And the non-oss version, is that one compiled by Microsoft? Does it include data collection?

**Comment by amtlib-dot-dll** [comment]
*Disclaimer: I'm not affiliated with Microsoft*

Good question

The "official" expatiation about it: https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005

Personally speaking,
* The proprietary (non-oss) version is compiled by Microsoft, distributed in their homepage https://code.visualstudio.com/; the open source version is compiled from code in the repo https://github.com/Microsoft/vscode with necessary dependencies
* Therefore, the proprietary version cannot be redistributed, that is, users can only download the binary from Microsoft's servers, and `flatpak` will also download the binary from Microsoft's server when you do `flatpak install flathub com.visualstudio.code` or `flatpak update`; the binary of the open source version is compiled by us, therefore it will be directly downloaded from our server
* The open source version is based on https://github.com/Microsoft/vscode/releases, so they are stable, and the proprietary version *should* also be based on it, though I'm not sure
* As explained in the readme file of this repo, there are two built-in extensions that is not included due to my laziness, but they can be downloaded from the marketplace when needed
* Apart from that, no other features should be missing. The marketplace is usable due to an interesting issue (you can dig into this recipe if you're also interested). Oh, the telemetry data collection and the Twitter feedback is stripped because they are not in the upstream repository. They should be in some private servers of Microsoft
* Aha, the logo of the proprietary version is also proprietary 😂

**Comment by martijnkruiten** [comment]
Thank you for the detailed explanation and even more so for doing this. This clears up any confusion I had and I'll continue using this version.

**Comment by Synapscident** [comment]
Thanks to both martijnkruiten and amtlib-dot-dll for the helpful explanation.

**Comment by hoshsadiq** [comment]
@amtlib-dot-dll out of curiousity how does this differ from vscodium?
